# Generated by Django 3.2.8 on 2021-10-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('firstname', models.TextField(max_length=100)),
                ('lastname', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('firstname', models.TextField(max_length=100)),
                ('lastname', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=200)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dabase.child')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dabase.parent')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(to='dabase.Parent'),
        ),
    ]
