# Generated by Django 3.2.8 on 2021-10-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dabase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='child_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='task',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dabase.child'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dabase.parent'),
        ),
    ]
